preproc = function(data){
  data[,`:=`( # application
             RATIO_ANNUITY_INCOME = AMT_ANNUITY / AMT_INCOME_TOTAL,
             RATIO_CREDIT_INCOME = AMT_CREDIT / AMT_INCOME_TOTAL,
             RATIO_CREDIT_GOODS = AMT_CREDIT / AMT_GOODS_PRICE, 
             RATIO_PAYMENT = AMT_ANNUITY / AMT_CREDIT, 
             RATIO_EMPLOYED_BIRTH = DAYS_EMPLOYED / DAYS_BIRTH,
             RATIO_CAR_BIRTH = OWN_CAR_AGE / DAYS_BIRTH,
             RATIO_CAR_EMPLOYED = OWN_CAR_AGE / DAYS_EMPLOYED,
             RATIO_PHONE_BIRTH = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
             RATIO_PHONE_EMPLOYED = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED,
             RATIO_CHILD = CNT_CHILDREN / CNT_FAM_MEMBERS,
             INCOME_per_FAM = AMT_INCOME_TOTAL / CNT_FAM_MEMBERS,
             INCOME_per_ADULT = AMT_INCOME_TOTAL / (CNT_FAM_MEMBERS - CNT_CHILDREN),
             CREDIT_per_FAM = AMT_CREDIT / CNT_FAM_MEMBERS,
             CREDIT_per_ADULT = AMT_CREDIT / (CNT_FAM_MEMBERS - CNT_CHILDREN),
             # variables at below added on 24 July
             # bureau
             RATIO_DEBT_CREDIT_BURUEA = AMT_CREDIT_SUM_DEBT_SUM / AMT_CREDIT_SUM_SUM,
             RATIO_OVERDUE_DEBT_BURUEA = AMT_CREDIT_SUM_OVERDUE_SUM / AMT_CREDIT_SUM_DEBT_SUM,
             # installments
             RATIO_INSTALMENT_PAST_FUTURE = CNT_INSTALMENT_MEAN / CNT_INSTALMENT_FUTURE_MEAN,
             # previous application
             RATIO_PAYMENT_PREV = AMT_ANNUITY_MEAN / AMT_CREDIT_MEAN,
             RATIO_CREDIT_RECEIVED_ASKED_PREV = AMT_CREDIT_MEAN / AMT_APPLICATION_MEAN,
             RATIO_CREDIT_ASKED_GOODS_PRICE_PREV = AMT_APPLICATION_MEAN / AMT_GOODS_PRICE_MEAN,
             RATIO_CREDIT_RECEIVED_GOODS_PRICE_PREV = AMT_CREDIT_MEAN / AMT_GOODS_PRICE_MEAN,
             DIFF_DAYS_LAST_DUE_PREV = DAYS_LAST_DUE_1ST_VERSION_MEAN - DAYS_LAST_DUE_MEAN, 
             # credit card
             RATIO_BALANCE_LIMIT_CCARD = AMT_BALANCE_MEAN / AMT_CREDIT_LIMIT_ACTUAL_MEAN,
             RATIO_INST_MIN_PAYMENT_CCARD = AMT_INST_MIN_REGULARITY_MEAN / AMT_PAYMENT_CURRENT_MEAN, # AMT_PAYMENT_TOTAL_CURRENT_MEAN?
             RATIO_PAYMENT_DRAWINGS_CCARD = AMT_PAYMENT_CURRENT_MEAN / AMT_DRAWINGS_CURRENT_MEAN,
             RATIO_PAYMENT_RECEIVABLE_CCARD = AMT_PAYMENT_CURRENT_MEAN / AMT_RECIVABLE_MEAN, # AMT_TOTAL_RECEIVABLE_MEAN?
             CCARD_DRAWING_CURRENT_per_CNT = AMT_DRAWINGS_CURRENT_MEAN / CNT_DRAWINGS_CURRENT_MEAN,
             CCARD_DRAWING_ATM_per_CNT = AMT_DRAWINGS_ATM_CURRENT_MEAN / CNT_DRAWINGS_ATM_CURRENT_MEAN,
             CCARD_DRAWING_OTHER_per_CNT = AMT_DRAWINGS_OTHER_CURRENT_MEAN / CNT_DRAWINGS_OTHER_CURRENT_MEAN,
             CCARD_DRAWING_POS_per_CNT = AMT_DRAWINGS_POS_CURRENT_MEAN / CNT_DRAWINGS_POS_CURRENT_MEAN
             ), by = "SK_ID_CURR"]
}