preproc = function(data){
  data[,`:=`( # application
             Add_RATIO_ANNUITY_INCOME = AMT_ANNUITY / AMT_INCOME_TOTAL,
             Add_RATIO_CREDIT_INCOME = AMT_CREDIT / AMT_INCOME_TOTAL,
             Add_RATIO_CREDIT_GOODS = AMT_CREDIT / AMT_GOODS_PRICE, 
             Add_RATIO_PAYMENT = AMT_ANNUITY / AMT_CREDIT, 
             Add_RATIO_EMPLOYED_BIRTH = DAYS_EMPLOYED / DAYS_BIRTH,
             Add_RATIO_CAR_BIRTH = OWN_CAR_AGE / DAYS_BIRTH,
             Add_RATIO_CAR_EMPLOYED = OWN_CAR_AGE / DAYS_EMPLOYED,
             Add_RATIO_PHONE_BIRTH = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
             Add_RATIO_PHONE_EMPLOYED = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED,
             Add_RATIO_CHILD = CNT_CHILDREN / CNT_FAM_MEMBERS,
             Add_INCOME_per_FAM = AMT_INCOME_TOTAL / CNT_FAM_MEMBERS,
             Add_INCOME_per_ADULT = AMT_INCOME_TOTAL / (CNT_FAM_MEMBERS - CNT_CHILDREN),
             Add_CREDIT_per_FAM = AMT_CREDIT / CNT_FAM_MEMBERS,
             Add_CREDIT_per_ADULT = AMT_CREDIT / (CNT_FAM_MEMBERS - CNT_CHILDREN),
             # variables at below added on 24 July
             # bureau
             Add_RATIO_SUM_DEBT_CREDIT_BURUEA = AMT_CREDIT_SUM_DEBT_SUM / AMT_CREDIT_SUM_SUM,
             Add_RATIO_SUM_OVERDUE_DEBT_BURUEA = AMT_CREDIT_SUM_OVERDUE_SUM / AMT_CREDIT_SUM_DEBT_SUM,
             # POS_CASH
             Add_RATIO_MEAN_INSTALMENT_PAST_FUTURE = CNT_INSTALMENT_MEAN / CNT_INSTALMENT_FUTURE_MEAN,
             # previous application
             Add_RATIO_MEAN_PAYMENT_PREV = AMT_ANNUITY_PREV_MEAN / AMT_CREDIT_MEAN,
             Add_RATIO_MEAN_CREDIT_RECEIVED_ASKED_PREV = AMT_CREDIT_MEAN / AMT_APPLICATION_MEAN,
             Add_RATIO_MEAN_CREDIT_ASKED_GOODS_PRICE_PREV = AMT_APPLICATION_MEAN / AMT_GOODS_PRICE_MEAN,
             Add_RATIO_MEAN_CREDIT_RECEIVED_GOODS_PRICE_PREV = AMT_CREDIT_MEAN / AMT_GOODS_PRICE_MEAN,
             Add_DIFF_MEAN_DAYS_LAST_DUE_PREV = DAYS_LAST_DUE_1ST_VERSION_MEAN - DAYS_LAST_DUE_MEAN, 
             # credit card
             Add_RATIO_MEAN_BALANCE_LIMIT_CARD = AMT_BALANCE_MEAN / AMT_CREDIT_LIMIT_ACTUAL_MEAN,
             Add_RATIO_MEAN_INST_MIN_PAYMENT_CARD = AMT_INST_MIN_REGULARITY_MEAN / AMT_PAYMENT_CURRENT_MEAN, # AMT_PAYMENT_TOTAL_CURRENT_MEAN?
             Add_RATIO_MEAN_PAYMENT_DRAWINGS_CARD = AMT_PAYMENT_CURRENT_MEAN / AMT_DRAWINGS_CURRENT_MEAN,
             Add_RATIO_MEAN_PAYMENT_RECEIVABLE_CARD = AMT_PAYMENT_CURRENT_MEAN / AMT_RECIVABLE_MEAN, # AMT_TOTAL_RECEIVABLE_MEAN?
             Add_MEAN_DRAWING_CURRENT_per_CNT_CARD = AMT_DRAWINGS_CURRENT_MEAN / CNT_DRAWINGS_CURRENT_MEAN,
             Add_MEAN_DRAWING_ATM_per_CNT_CARD = AMT_DRAWINGS_ATM_CURRENT_MEAN / CNT_DRAWINGS_ATM_CURRENT_MEAN,
             Add_MEAN_DRAWING_OTHER_per_CNT_CARD = AMT_DRAWINGS_OTHER_CURRENT_MEAN / CNT_DRAWINGS_OTHER_CURRENT_MEAN,
             Add_MEAN_DRAWING_POS_per_CNT_CARD = AMT_DRAWINGS_POS_CURRENT_MEAN / CNT_DRAWINGS_POS_CURRENT_MEAN
             ), by = "SK_ID_CURR"]
}