preproc = function(data){
  data[,`:=`(RATIO_ANNUITY_INCOME = AMT_ANNUITY / AMT_INCOME_TOTAL,
             RATIO_CREDIT_INCOME = AMT_CREDIT / AMT_INCOME_TOTAL,
             RATIO_CREDIT_GOODS = AMT_CREDIT / AMT_GOODS_PRICE, 
             RATIO_PAYMENT = AMT_ANNUITY / AMT_CREDIT, 
             RATIO_EMPLOYED_BIRTH = DAYS_EMPLOYED / DAYS_BIRTH,
             RATIO_CAR_BIRTH = OWN_CAR_AGE / DAYS_BIRTH,
             RATIO_CAR_EMPLOYED = OWN_CAR_AGE / DAYS_EMPLOYED,
             RATIO_PHONE_BIRTH = DAYS_LAST_PHONE_CHANGE / DAYS_BIRTH,
             RATIO_PHONE_EMPLOYED = DAYS_LAST_PHONE_CHANGE / DAYS_EMPLOYED,
             RATIO_CHILD = CNT_CHILDREN / CNT_FAM_MEMBERS,
             INCOME_per_FAM = AMT_INCOME_TOTAL / CNT_FAM_MEMBERS,
             INCOME_per_ADULT = AMT_INCOME_TOTAL / (CNT_FAM_MEMBERS - CNT_CHILDREN),
             CREDIT_per_FAM = AMT_CREDIT / CNT_FAM_MEMBERS,
             CREDIT_per_ADULT = AMT_CREDIT / (CNT_FAM_MEMBERS - CNT_CHILDREN)), by = "SK_ID_CURR"]
}